services:
    postgres:
        image: postgres:17-alpine
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - app-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s

    backend:
        build:
            context: ./backend
        environment:
            NODE_ENV: production
            DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
            JWT_SECRET: ${JWT_SECRET}
            JWT_ACCESS_TTL: ${JWT_ACCESS_TTL}
            JWT_REFRESH_TTL: ${JWT_REFRESH_TTL}
            COOKIE_DOMAIN: ${COOKIE_DOMAIN}
        depends_on:
            postgres:
                condition: service_healthy
        networks:
            - app-network
        ports:
            - 3000:3000
    
    nginx:
        depends_on:
            - backend
        build:
            context: ./frontend
        volumes:
            - certificates:/etc/letsencrypt
            - data:/data/letsencrypt
        ports:
            - 80:80
            - 443:443
        networks:
            - app-network
    
    certbot: 
        image: certbot/certbot
        depends_on:
            - nginx
        volumes:
            - certificates:/etc/letsencrypt
            - data:/data/letsencrypt
        command: certonly --webroot -webroot-path=/data/letsencrypt --keep-until-expiring --agree-tos --email holakarmos@gmail.com --no-eff-email -d nota-tg-bot.ru  # --staging for tests --keep-until-expiring istead of --force-renewal
        networks:
            - app-network

volumes:
    postgres_data:
    certificates:
    data:

networks:
    app-network:
        driver: bridge